---
- name: Install server
  package: name={{ item }} state=present
  with_items:
    - nginx
  notify:
    - start nginx

- name: Change default configuration
  template:
    src: default
    dest: /etc/nginx/sites-available/default
  notify:
    - reload nginx
